# install with conda env create -f environment.yml 
name: 'data-cleaning'
channels:
  - conda-forge
  - pytorch
  - anaconda
  - plotly
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - ipykernel
  - jupyterlab
  - matplotlib
  - seaborn
  - pyodbc
  - sqlalchemy
  - tqdm
  - ipython
  - pip
  - pip:
      - openai
      - python-dotenv
      - urllib3