# install with conda env create -f environment.yml 
name: 'heymate-mds-data-clean-pipeline'
channels:
  - conda-forge
  - pytorch
  - anaconda
  - plotly
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.3
  - numpy=2.2.6
  - requests=2.32.3
  - ipykernel=6.29.5
  - jupyterlab=4.4.3
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - scikit-learn=1.6.1
  - joblib=1.5.1
  - threadpoolctl=3.6.0
  - freetds=1.5.1
  - pymssql=2.3.4
  - altair=5.5.0
  - sqlalchemy=2.0.41
  - tqdm=4.67.1
  - ipython=9.2.0
  - urllib3=2.4.0
  - pip
  - pip:
      - openai==1.82.1
      - python-dotenv==1.1.0
      - azure-functions==1.23.0
      - flask==3.1.1