name: Deployment Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          auto-activate-base: false
          activate-environment: heymate-mds-data-clean-pipeline
          python-version: 3.9

      - name: Show Python version
        shell: bash -l {0}
        run: python --version

      - name: Make credentials directory
        run: mkdir -p credentials

      - name: Write OpenAI token
        run: echo "${{ secrets.OPENAI_API_KEY }}" > credentials/open_ai_token.txt

      - name: Write DB key (.env or other multi-line)
        run: |
          printf '%s' "${{ secrets.DB_KEY }}" > credentials/.env

      - name: Run deployment test
        shell: bash -l {0}
        run: |
          cd script
          python deployment_test.py

  deploy-to-azure:
    needs: test-deployment  # Wait for testing job to complete
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: heymate-popularity-func  # Your Azure Function App name
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: ./script # Deploy from root (adjust if function app is in subfolder)
