name: "CI/CD Test & Deploy Azure Function"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_FUNCTIONAPP_NAME: 'heymate-popularity-func'   # replace as needed
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './script'  # path to your function code
  PYTHON_VERSION: '3.11'

jobs:
  test-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml      # <-- at root
          auto-activate-base: false
          activate-environment: heymate-mds-data-clean-pipeline
          python-version: 3.11

      - name: Show Python version
        shell: bash -l {0}
        run: python --version

      - name: Make credentials directory
        run: mkdir -p credentials

      - name: Write OpenAI token
        run: echo "${{ secrets.OPENAI_API_KEY }}" > credentials/open_ai_token.txt

      - name: Write DB key (.env or other multi-line)
        run: |
          printf '%s' "${{ secrets.DB_KEY }}" > credentials/.env

      - name: Run deployment test
        shell: bash -l {0}
        run: |
          cd script
          python credential_validation_test_unit.py
